# RIVR Release Build Makefile
#
# Usage:
#   make version           — stamps pubspec version as <year>.<major>.<minor>+<commits>
#   make release-android   — builds signed release AAB with obfuscation
#   make release-ios       — builds release IPA with obfuscation
#   make upload-symbols    — uploads iOS dSYMs to Crashlytics (run after release-ios)
#   make analyze           — runs flutter analyze
#   make test              — runs unit + widget tests
#
# Prerequisites:
#   - android/key.properties must exist (see Google Drive → RIVR Release Keys/)
#   - lib/services/0_config/shared/config.dart must exist (copy from config.template.dart)
#   - lib/firebase_options.dart must exist (generated by FlutterFire CLI)
#
# Two different kinds of symbols, easy to confuse — the previous note here got
# it wrong and cost an evening during the 2026.0.0 release:
#
#   build/debug-info/            Dart obfuscation map. Feeds `flutter symbolize`
#                                to read obfuscated DART stack traces. NOT a
#                                dSYM and NOT accepted by Crashlytics.
#
#   <archive>/dSYMs/             Native debug symbols. What Crashlytics wants,
#                                so NATIVE crashes resolve to real frames.
#
# `firebase crashlytics:symbols:upload` is for Android NDK symbols. Pointed at
# either of the above it fails with an unhelpful "java command failed". iOS
# dSYMs go through Crashlytics' own upload-symbols binary — see
# `make upload-symbols`.
#
# Keep build/debug-info/ for the lifetime of the release either way: without it
# obfuscated Dart traces from TestFlight are unreadable.

DEBUG_INFO_DIR := build/debug-info

.PHONY: version release-android release-ios upload-symbols analyze test clean

# Version scheme
# --------------
# <year>.<major>.<minor>+<commit count>, e.g. 2026.0.0+521
#
# The build number is the repository's commit count, so it is derived rather
# than remembered — there is no number to forget to increment, and it always
# rises. Both stores require a strictly increasing build number and silently
# reject a repeat, which is the failure this removes.
#
# Run this on `main` at release time, after merging. Commit counts differ per
# branch, and a feature branch can report FEWER commits than main; stamping
# from one would produce a number the stores refuse.
#
# The +1 accounts for the commit that carries the stamp itself, so the number
# in pubspec matches the commit it ships as.
#
# YEAR/MAJOR/MINOR are set by hand: bump MAJOR for a release users would
# notice, MINOR for fixes, YEAR when the calendar does.
YEAR  ?= 2026
MAJOR ?= 0
MINOR ?= 0

version:
	@BRANCH=$$(git rev-parse --abbrev-ref HEAD); \
	if [ "$$BRANCH" != "main" ]; then \
		echo "refusing to stamp from '$$BRANCH' — commit counts are branch-specific."; \
		echo "run this on main, after merging development."; exit 1; \
	fi; \
	if [ -n "$$(git status --porcelain --untracked-files=no)" ]; then \
		echo "refusing to stamp a dirty tree — commit or stash first."; exit 1; \
	fi; \
	BUILD=$$(( $$(git rev-list --count HEAD) + 1 )); \
	NEW_VER="$(YEAR).$(MAJOR).$(MINOR)"; \
	NEW="$$NEW_VER+$$BUILD"; \
	OLD=$$(grep '^version:' pubspec.yaml | awk '{print $$2}'); \
	OLD_BUILD=$$(echo "$$OLD" | sed 's/.*+//'); \
	OLD_VER=$$(echo "$$OLD" | sed 's/+.*//'); \
	if [ "$$BUILD" -le "$$OLD_BUILD" ]; then \
		echo "refusing to go backwards: $$OLD -> $$NEW"; exit 1; \
	fi; \
	LOWEST=$$(printf '%s\n%s\n' "$$OLD_VER" "$$NEW_VER" | sort -t. -k1,1n -k2,2n -k3,3n | head -1); \
	if [ "$$NEW_VER" != "$$OLD_VER" ] && [ "$$LOWEST" = "$$NEW_VER" ]; then \
		echo "refusing to go backwards: $$OLD -> $$NEW"; \
		echo "MAJOR and MINOR both default to 0 — pass both, e.g. make version MAJOR=1 MINOR=1"; \
		exit 1; \
	fi; \
	sed -i '' "s/^version: .*/version: $$NEW/" pubspec.yaml; \
	echo "$$OLD  ->  $$NEW"; \
	echo "now: commit pubspec.yaml + app_releases.md, then make release-ios"


release-android:
	flutter build appbundle --release \
		--obfuscate \
		--split-debug-info=$(DEBUG_INFO_DIR)/android

release-ios:
	flutter build ipa --release \
		--obfuscate \
		--split-debug-info=$(DEBUG_INFO_DIR)/ios

analyze:
	flutter analyze

test:
	flutter test

clean:
	flutter clean

# Upload iOS dSYMs to Crashlytics.
# --------------------------------
# Run after `make release-ios`, while build/ios/ is still populated. The
# upload-symbols binary ships inside the Firebase SDK checkout, which since the
# Swift Package Manager migration lives under build/ios/SourcePackages rather
# than ios/Pods — so a `flutter clean` removes it and this target has to be run
# from a fresh build, not months later.
UPLOAD_SYMBOLS := build/ios/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols
DSYMS_DIR      := build/ios/archive/Runner.xcarchive/dSYMs
GSP            := ios/Runner/GoogleService-Info.plist

upload-symbols:
	@if [ ! -x "$(UPLOAD_SYMBOLS)" ]; then \
		echo "upload-symbols not found at $(UPLOAD_SYMBOLS)"; \
		echo "it is created by an iOS build — run 'make release-ios' first."; exit 1; \
	fi
	@if [ ! -d "$(DSYMS_DIR)" ]; then \
		echo "no dSYMs at $(DSYMS_DIR) — run 'make release-ios' first."; exit 1; \
	fi
	@if [ ! -f "$(GSP)" ]; then \
		echo "missing $(GSP) — it is gitignored; restore it before releasing."; exit 1; \
	fi
	@echo "uploading $$(ls $(DSYMS_DIR) | wc -l | tr -d ' ') dSYMs to Crashlytics..."
	@$(UPLOAD_SYMBOLS) -gsp $(GSP) -p ios $(DSYMS_DIR)
