// functions/src/store-keys.ts
//
// The document-ID contract for the cloud store (ADR 0011 Phase 4).
//
// Phase 4 requires that a stored document's ID *is* the client's cache key:
//
//   "Per-reach documents at `nwm__<reachId>__<product>`, matching
//    RiverDataKey.storageKey so the document ID *is* the client cache key."
//
// That makes this file one half of a cross-language contract. The other half is
// Dart:
//
//   lib/models/1_domain/shared/river_data/river_data_key.dart   (storageKey)
//   lib/models/1_domain/shared/forecast_source.dart             (ForecastSource)
//   lib/models/1_domain/shared/river_data/forecast_product.dart (ForecastProduct)
//
// Both Dart enums define `String get id => name`, so the wire strings are the
// enum identifiers verbatim — camelCase, not snake_case.
//
// **Why this is dangerous enough to need its own file and its own tests.** If
// the server writes `nwm__123__medium_range` while the app reads
// `nwm__123__mediumRange`, nothing errors. The write succeeds, the read finds
// no document, and Phase 5 quietly falls back to fetching upstream — the exact
// failure this ADR exists to remove, with no symptom other than the store
// appearing to do nothing. Five operations in this repo have already exited 0
// while producing wrong or partial data (CLAUDE.md); this would be the sixth.
//
// So: never hand-write one of these strings. Call storageKey().

/** Mirrors Dart `ForecastSource` — the values of `ForecastSource.id`. */
export const FORECAST_SOURCES = ["nwm", "geoglows"] as const;
export type ForecastSourceId = typeof FORECAST_SOURCES[number];

/**
 * Mirrors Dart `ForecastProduct` — the values of `ForecastProduct.id`, in
 * declaration order.
 *
 * Ten entries. `geoglowsEnsemble` terminates the Dart enum with `;` rather than
 * `,`, which is exactly how it gets dropped when this list is regenerated by
 * pattern-matching the source. Count before trusting.
 */
export const FORECAST_PRODUCTS = [
  "analysisAssimilation",
  "reachSummary",
  "reachMetadata",
  "shortRange",
  "mediumRange",
  "longRange",
  "mediumRangeBlend",
  "returnPeriods",
  "geoglowsForecast",
  "geoglowsEnsemble",
] as const;
export type ForecastProductId = typeof FORECAST_PRODUCTS[number];

/**
 * The Firestore collection holding the cloud store (ADR 0011 Phase 4).
 *
 * Named for the app's RiverDataKey/RiverDataEntry pair, in the snake_case the
 * project's other collections use (`users`, `publish_cadence_log`,
 * `return_period_cache`). The ADR does not name it; this is the implementation
 * choice, and firestore.rules must match it exactly or the client is denied.
 */
export const STORE_COLLECTION = "river_data";

/** Separator between key segments. Two underscores, per RiverDataKey. */
const SEPARATOR = "__";

/**
 * The Firestore document ID for one (source, reach, product) triple.
 *
 * Equivalent to Dart's `RiverDataKey.storageKey`:
 *   `'${source.id}__${reachId}__${product.id}'`
 *
 * @param {ForecastSourceId} source - Which network the reach belongs to.
 * @param {string} reachId - The reach identifier within that source.
 * @param {ForecastProductId} product - Which product this document holds.
 * @return {string} e.g. `nwm__23021904__shortRange`.
 */
export function storageKey(
  source: ForecastSourceId,
  reachId: string,
  product: ForecastProductId
): string {
  if (!reachId) {
    throw new Error("storageKey: reachId must not be empty");
  }
  if (reachId.includes(SEPARATOR)) {
    // A reach id containing the separator would make the key ambiguous to
    // parse back, and Phase 4's GC and monitoring both parse keys.
    throw new Error(
      `storageKey: reachId "${reachId}" must not contain "${SEPARATOR}"`
    );
  }
  return `${source}${SEPARATOR}${reachId}${SEPARATOR}${product}`;
}

/** A parsed storage key. */
export interface ParsedStorageKey {
  source: ForecastSourceId;
  reachId: string;
  product: ForecastProductId;
}

/**
 * Inverse of [storageKey]. Returns null rather than throwing, because the
 * caller is usually iterating a collection that may contain foreign documents
 * and one stray ID should not abort a whole run.
 *
 * @param {string} key - A document ID to parse.
 * @return {ParsedStorageKey | null} The parsed triple, or null if the ID is not
 *   a well-formed store key with a recognised source and product.
 */
export function parseStorageKey(key: string): ParsedStorageKey | null {
  const parts = key.split(SEPARATOR);
  if (parts.length !== 3) return null;
  const [source, reachId, product] = parts;
  if (!reachId) return null;
  if (!(FORECAST_SOURCES as readonly string[]).includes(source)) return null;
  if (!(FORECAST_PRODUCTS as readonly string[]).includes(product)) return null;
  return {
    source: source as ForecastSourceId,
    reachId,
    product: product as ForecastProductId,
  };
}
