// CI stub for firebase_options.dart.
// Committed to the repo so GitHub Actions can copy it to firebase_options.dart
// before running flutter analyze and flutter test.
// The real firebase_options.dart is gitignored and generated by FlutterFire CLI.
//
// Usage (in CI workflow):
//   cp lib/firebase_options.ci.dart lib/firebase_options.dart
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'CI_PLACEHOLDER',
    appId: 'CI_PLACEHOLDER',
    messagingSenderId: 'CI_PLACEHOLDER',
    projectId: 'CI_PLACEHOLDER',
    storageBucket: 'CI_PLACEHOLDER',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CI_PLACEHOLDER',
    appId: 'CI_PLACEHOLDER',
    messagingSenderId: 'CI_PLACEHOLDER',
    projectId: 'CI_PLACEHOLDER',
    storageBucket: 'CI_PLACEHOLDER',
    iosBundleId: 'CI_PLACEHOLDER',
  );
}
